---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    # datasource=ruby-version depName=ruby
    - command: /home/isucon/.xbuild/ruby-install 3.2.2 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v4.4.3 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
      tags:
        - nodejs
    # golang
    # datasource=golang-version depName=golang
    - shell: /home/isucon/.xbuild/go-install 1.20.4 /home/isucon/.local/go $(uname -s | tr [A-Z] [a-z]) $(dpkg --print-architecture)
      args:
        creates: /home/isucon/.local/go/bin/go
